### ISSUE TITLE
Replace input.csv and output.csv for {api_name}_input.csv and {api_name}_output.csv

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia-pack#52]
At the moment, Ersilia Pack looks for input.csv and output.csv files. However, I think it is safer to name those files run_input.csv and run_output.csv, where "run" is the API endpoint. This will allow us to extend the Ersilia Pack module in the future and allow for other enpoints such as "fit" (or "train").

Therefore, we need Ersilia Pack to work swiftly with files named run_input.csv and run_output.csv. At the moment, this is not the case, producing a file not found error:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/mduranfrigola/eos/repository/eos3b5e/20250224-5fd831e7-eb52-4707-bf4d-7ad6a0a92a90/model/framework/examples/output.csv'`

Importantly, for backwards compatibility, we still want to allow for input.csv and output.csv.

I suggest the following, to avoid ambiguity:
* If **only** two files are available in the examples/ folder, work indistinctively with input.csv/output.csv or run_input.csv/run_output.csv
* If **more than** two files are available in the examples/ folder, force that the api_name is specified, in this case, run_input.csv/run_output.csv

**Comment by GemmaTuron** [comment]
Hi @Abellegese 


The reason I was not able to build images is precisely this, I only have run_input and run_output now but ersilia pack is looking into input.csv and output.csv only.
Could you change this to the format than Miquel suggests as a priority, and push to the main repo please?

**Comment by Abellegese** [comment]
Yes @GemmaTuron this is fixed.

**Comment by GemmaTuron** [comment]
Hi @Abellegese and @miquelduranfrigola 

As long as it is in a branch is not solved, as the workflows are looking into the main branch and this one is still fixed to input and output.
@Abellegese your fix allows for both types of files or only {api}_input {api}_output?

**Comment by Abellegese** [comment]
Hi @GemmaTuron currently it only looks for  api_input and api_output.

**Comment by GemmaTuron** [comment]
Hi @Abellegese 

I think that what Miquel mentions in the original issue is important: **Importantly, for backwards compatibility, we still want to allow for input.csv and output.csv.**
Is this possible?

**Comment by Abellegese** [comment]
Yes @GemmaTuron I did that.

**Comment by GemmaTuron** [comment]
sorry @Abellegese maybe a bit of communication confusion:

In your previous message you say: currently it only looks for api_input and api_output. - you mean your branch only looks for api_input api_output or, as you say in your second message, the changes in your branch allow for both?

**Comment by Abellegese** [comment]
I mean it was only api_{}.csv but I fixed that to work for both. its pushed now.

**Comment by GemmaTuron** [comment]
This is completed.
